name: Daily GX Games Poster

on:
  schedule:
    - cron: '0 14 * * *' # 10 AM EST
  workflow_dispatch:

jobs:
  post-games:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run Script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py
